---

- name: Adjust php.ini file seetings
  lineinfile:
    dest: /etc/php/7.3/apache2/php.ini
    regexp: 'upload_max_filesize ='
    line: 'upload_max_filesize = 6M'
  tags:
    - suitecrm
    
# - name: composer install
#   composer:
#     command: install
#     working_dir: "{{ apache.docroot }}" 
#   tags:
#   - suitecrm-composer
#   - suitecrm
  