---
server:
    install: '1'
    timezone: UTC
    locale: en_GB.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: "{{ vagrant_name }}", ip: "{{ vagrant_ip }}", memory: "{{ vagrant_memory }}", sharedfolder: /vagrant, useVagrantCloud: '1', syncType: nfs }
apache:
    install: '1'
    docroot: /vagrant
    servername: crmtests.tilnet.co.il
mysql:
    install: '1'
    root_password: 'Hv2lnttVOh'
    database: db
    test_database: db-tests
    user: chen
    password: Hv2lnttVOh
    dump: ''
    tests_dump: ''
php:
    install: '1'
    ppa: php7
    version: '7.3'

xdebug_remote_enable: 1
xdebug_remote_port: 9001
xdebug_remote_connect_back: 1    
            
suitecrm:
    url: "{{ apache.docroot }}/{{ apache.servername }}"
    backup_dir: /backup
    db_backup_name: "{{ apache.docroot }}/crm-backup.sql"
    tests:
        database_driver: MYSQL
        admin_user: tester
        admin_password: 123

selenium_port: 9515

    
    
