---
- hosts: all
  become: yes
  vars_files:
    - ../vagrant.default.yml
    - vars/all.yml
  handlers:
    - name: reload php-fpm
      service:
        name: "php{{ php.version }}-fpm"
        state: reloaded   
        
    - name: reload apache2
      service:
        name: "apache2"
        state: reloaded        
  roles:
    - server
    - vagrant_local
    - apache
    - mysql
    - php
    - xdebug
    - app
    - composer
    - role: geerlingguy.java
      tags: [java]
    - role: arknoll.selenium_fork
      tags: [selenium]
      vars:
        selenium_version: "3.141.59"
        selenium_install_firefox: no
        selenium_install_chrome: yes    
    - suitecrm
    - elastic_search

    

